# Generated by Django 5.0.1 on 2024-02-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_alter_tournament_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tosearch', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='Tournament', max_length=255),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='picture',
            field=models.ImageField(default='media/default.jpeg', upload_to=''),
        ),
    ]
