# Generated by Django 5.0.1 on 2024-02-28 03:21

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_searchtournament_tournament_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchTournament',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='time_for_registration_left',
        ),
        migrations.AddField(
            model_name='tournament',
            name='alreadyin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='tournament',
            name='teamsallowed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='whoisowner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
