# Generated by Django 5.0.1 on 2024-02-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_delete_searchtournament_remove_tournament_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='formatt',
            field=models.CharField(choices=[('single', 'Single'), ('team', 'Team')], default='single', max_length=10),
        ),
    ]
