# Generated by Django 5.0.1 on 2024-02-28 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_tournament_formatt'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='players',
            field=models.IntegerField(default=0),
        ),
    ]
