# Generated by Django 5.0.1 on 2024-03-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_tournament_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='cyberSports',
            field=models.CharField(default='cybersports', max_length=255),
        ),
        migrations.AddField(
            model_name='tournament',
            name='sports',
            field=models.CharField(default='sports', max_length=255),
        ),
        migrations.AddField(
            model_name='tournament',
            name='typee',
            field=models.CharField(choices=[('sports', 'Sport'), ('cybersports', 'Cybersport')], default='sports', max_length=11),
        ),
    ]
