# Generated by Django 5.0.1 on 2024-02-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participating', '0002_coupon_request_cupon_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='cupon',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='request',
            name='cupon',
            field=models.CharField(default='uUka7Q', max_length=10),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
